# Generated by Django 2.1.2 on 2019-08-29 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackendMovie',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                ('backend', models.CharField(max_length=100)),
                ('fetched', models.DateTimeField(auto_now=True)),
                (
                    'movie',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='backend_movie',
                        to='mlist.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='BackendMovieAttribute',
            fields=[
                (
                    'id', models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BackendMovieBooleanAttribute',
            fields=[
                (
                    'backendmovieattribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='mlist.BackendMovieAttribute')),
                ('value', models.BooleanField()),
            ],
            bases=('mlist.backendmovieattribute',),
        ),
        migrations.CreateModel(
            name='BackendMovieDateAttribute',
            fields=[
                (
                    'backendmovieattribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='mlist.BackendMovieAttribute')),
                ('value', models.DateField()),
            ],
            bases=('mlist.backendmovieattribute',),
        ),
        migrations.CreateModel(
            name='BackendMovieDateTimeAttribute',
            fields=[
                (
                    'backendmovieattribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='mlist.BackendMovieAttribute')),
                ('value', models.DateTimeField()),
            ],
            bases=('mlist.backendmovieattribute',),
        ),
        migrations.CreateModel(
            name='BackendMovieFloatAttribute',
            fields=[
                (
                    'backendmovieattribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='mlist.BackendMovieAttribute')),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=200)),
            ],
            bases=('mlist.backendmovieattribute',),
        ),
        migrations.CreateModel(
            name='BackendMovieIntAttribute',
            fields=[
                (
                    'backendmovieattribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='mlist.BackendMovieAttribute')),
                ('value', models.IntegerField()),
                ('unit', models.CharField(max_length=200)),
            ],
            bases=('mlist.backendmovieattribute',),
        ),
        migrations.CreateModel(
            name='BackendMovieJSONAttribute',
            fields=[
                (
                    'backendmovieattribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='mlist.BackendMovieAttribute')),
                ('value', models.TextField()),
            ],
            bases=('mlist.backendmovieattribute',),
        ),
        migrations.CreateModel(
            name='BackendMovieStringAttribute',
            fields=[
                (
                    'backendmovieattribute_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='mlist.BackendMovieAttribute')),
                ('value', models.TextField()),
            ],
            bases=('mlist.backendmovieattribute',),
        ),
        migrations.AddField(
            model_name='backendmovieattribute',
            name='backend_movie',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='attributes',
                to='mlist.BackendMovie'),
        ),
        migrations.AlterUniqueTogether(
            name='backendmovieattribute',
            unique_together={('backend_movie', 'key')},
        ),
    ]
